[theme]
primaryColor = "#a78bfa"               # Soft lavender
backgroundColor = "#fdf9ff"            # Gentle floral white
secondaryBackgroundColor = "#f3e8ff"   # Light purple wash
textColor = "#2d2d2d"
font = "sans serif"